apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: file-cleaner
spec:
  selector:
    matchLabels:
      app: file-cleaner
  template:
    metadata:
      labels:
        app: file-cleaner
    spec:
      containers:
      - name: file-cleaner-container
        image: busybox:stable
        command: ['sh', '-c', 'while true; do rm `ls -t /data/* | awk "NR>5"`; ls -l /data; sleep 60; done']
        volumeMounts:
        - name: host-vol
          mountPath: /data
      volumes:
      - name: host-vol
        hostPath:
          path: /var/web/data
          type: Directory
