# A quick fedora pod
# Create: kubectl run fedora --dry-run=client -o yaml --image=fedora --command -- sh '-c' 'sleep 3600' | tee fedora.yaml
# List:   kubectl get pods -o wide 
# Test:   kubectl exec fedora -- uname -a
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fedora
  name: fedora
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: fedora
    name: fedora
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
