apiVersion: v1
kind: Pod
metadata:
  name: emptydir-sizelimit
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        ephemeral-storage: "1Gi"
      limits:
        ephemeral-storage: "2Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: /usr/share/nginx/html
  - name: alpine
    image: alpine
    command: ['sh', '-c', 'apk --update add curl; while true; do echo "$HOSTNAME: `date` : Welcome to Nginx! Hosted on emptyDir, testing resource requests and limits!!" >> /html/index.html; sleep 10; done']
    resources:
      requests:
        ephemeral-storage: "1Gi"
      limits:
        ephemeral-storage: "2Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/html"
  volumes:
    - name: ephemeral
      emptyDir:
        sizeLimit: 500Mi
