apiVersion: v1
kind: Pod
metadata:
  name: emptydir-memory
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: memory-volume
  - name: fedora-container
    image: fedora
    command: ['sh', '-c', 'while true; do echo "$HOSTNAME: `date` : Welcome to Nginx! Hosted on emptyDir Memory Volume!!" >> /html/index.html; sleep 10; done']
    volumeMounts:
    - name: memory-volume
      mountPath: /html
  volumes:
  - name: memory-volume
    emptyDir:
      medium: Memory
