# An alpine pod (https://hub.docker.com/_/alpine)
# Create: kubectl run alpine --dry-run=client -o yaml --image=alpine | tee alpine.yaml
# Quick:  kubectl run -it alpine --image=alpine --restart=Never
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine
  name: alpine
spec:
  containers:
  - image: alpine
    name: alpine
    command: ['sh', '-c', 'apk --update add curl; sleep 3600']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
