apiVersion: v1
kind: Pod
metadata:
  name: cm-consumer-pod-01
spec:
  containers:
    - name: cm-consumer-pod-01-container
      image: radial/busyboxplus
      command: [ '/bin/sh', '-c', 'env ; echo "CMENV_01_NGINX_CONF_DIR: [$[CMENV_01_NGINX_CONF_DIR]\nCMENV_02_NODE_PORT: [$(CMENV_02_NODE_PORT]"']
      env:
        - name: CMENV_01_NGINX_CONF_DIR
          valueFrom:
            configMapKeyRef:
              name: cm-01
              key: confdir
        - name: CMENV_02_NODE_PORT
          valueFrom:
            configMapKeyRef:
              name: cm-02
              key: node_port
  restartPolicy: Never
