apiVersion: v1
kind: Pod
metadata:
  name: cm-consumer-pod-01
spec:
  containers:
    - name: test-container
      image: radial/busyboxplus
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: CMENV_01_NGINX_CONF_DIR
          valueFrom:
            configMapKeyRef:
              name: cm-01
              key: confdir
        - name: CMENV_02_NODE_PORT
          valueFrom:
            configMapKeyRef:
              name: cm-02
              key: node_port
  restartPolicy: Never
