apiVersion: v1
kind: Service
metadata:
  name: sa-service
  namespace: mkdemo
spec:
  selector:
    app: sa-nginx
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
